- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-scenario003
      - puppet-openstack-beaker-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-horizon-tripleo-standalone
    gate:
      jobs:
        - puppet-horizon-tripleo-standalone

- job:
    name: puppet-horizon-tripleo-standalone
    parent: tripleo-puppet-ci-centos-8-standalone
    description: |
      TripleO standalone Job running Horizon specific Tempest tests.
    vars:
      build_container_images: true
      featureset_override:
        run_tempest: false
        tempest_services:
          - horizon
        tempest_test_whitelist:
          - 'horizon'
          - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps'
        use_os_tempest: true
